version: "3.9"
services:

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - 15672:15672
      - 5672:5672

  redis:
    image: "redis"
    ports:
      - 6379:6379

  postgresql:
    image: "postgres:13"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./setup/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql

#  app1:
#    build: .
#    restart: on-failure
#    depends_on:
#      - redis
#      - postgresql
#      - rabbitmq
#    ports:
#      - 8081:8080
#    env_file:
#      ./setup/.env
#
#  app2:
#    build: .
#    restart: on-failure
#    depends_on:
#      - app1
#    ports:
#      - 8082:8080
#    env_file:
#      - ./setup/.env
#
#  app3:
#    build: .
#    restart: on-failure
#    depends_on:
#      - app2
#    ports:
#      - 8083:8080
#    env_file:
#      - ./setup/.env
#
#  app4:
#    build: .
#    restart: on-failure
#    depends_on:
#      - app3
#    ports:
#      - 8084:8080
#    env_file:
#      - ./setup/.env
